/* Şablon DSL: kısa spec → katman tabanlı şablon.
   spec = {
     key, name, desc:{en,tr}, tags:[style etiketleri], cats:[app store kategorileri], theme:'light|dark|colourful', skill:'simple|advanced', free?:bool, orientation?:'portrait|landscape',
     style: { font, weight, size, color, accent, hlStyle, align, letterSpacing, lineHeight, uppercase, decoration, box, boxColor,
              subFont, subWeight, subSize, subColor, subOpacity, titleH, subGap },
     bg: {...ekran arka planı varsayılanı}, pbg: {...proje panoramik arka planı}, panorama: bool,
     device: { frame, color, shadow, glare, fit, glow, glowStrength, homeIndicator },
     screens: [ { layout, title, sub, bg, dev, titleStyle, subStyle, under:[metnin altına çizilen öğeler], els:[ {kind, x, y, size, text, ...} ], extra:[ham katmanlar] } ]
   } */
(function (global) {
  const { newLayer } = global.Model;
  const clone = (v) => JSON.parse(JSON.stringify(v));

  /* düzenler: başlık/alt başlık kutuları ve cihaz kutusu (yüzde) */
  const LAYOUTS = {
    'text-top': { title: { x: 6, y: 5, w: 88, h: 21, align: 'center' }, sub: { x: 8, y: 18.5, w: 84, h: 6, align: 'center' }, dev: { x: 17, y: 27, w: 66, rot: 0 } },
    'text-top-left': { title: { x: 6, y: 5, w: 88, h: 21, align: 'left' }, sub: { x: 6, y: 18.5, w: 84, h: 6, align: 'left' }, dev: { x: 17, y: 27, w: 66, rot: 0 } },
    'text-bottom': { title: { x: 6, y: 68, w: 88, h: 21, align: 'center' }, sub: { x: 8, y: 87.5, w: 84, h: 6, align: 'center' }, dev: { x: 19, y: 4, w: 62, rot: 0 } },
    'text-bottom-left': { title: { x: 6, y: 68, w: 88, h: 21, align: 'left' }, sub: { x: 6, y: 87.5, w: 84, h: 6, align: 'left' }, dev: { x: 19, y: 4, w: 62, rot: 0 } },
    'bleed': { title: { x: 6, y: 5, w: 88, h: 21, align: 'center' }, sub: { x: 8, y: 18.5, w: 84, h: 6, align: 'center' }, dev: { x: 8, y: 30, w: 84, rot: 0 } },
    'bleed-left': { title: { x: 6, y: 5, w: 88, h: 21, align: 'left' }, sub: { x: 6, y: 18.5, w: 84, h: 6, align: 'left' }, dev: { x: 8, y: 30, w: 84, rot: 0 } },
    'hero': { title: { x: 6, y: 5, w: 88, h: 21, align: 'center' }, sub: { x: 8, y: 18.5, w: 84, h: 6, align: 'center' }, dev: { x: 10, y: 31, w: 96, rot: -7 } },
    'tilt': { title: { x: 6, y: 5, w: 88, h: 21, align: 'center' }, sub: { x: 8, y: 18.5, w: 84, h: 6, align: 'center' }, dev: { x: 18, y: 29, w: 64, rot: -8 } },
    'tilt-r': { title: { x: 6, y: 5, w: 88, h: 21, align: 'center' }, sub: { x: 8, y: 18.5, w: 84, h: 6, align: 'center' }, dev: { x: 18, y: 29, w: 64, rot: 8 } },
    'right': { title: { x: 6, y: 6, w: 80, h: 21, align: 'left' }, sub: { x: 6, y: 19.5, w: 78, h: 6, align: 'left' }, dev: { x: 42, y: 33, w: 64, rot: 7 } },
    'left': { title: { x: 14, y: 6, w: 80, h: 21, align: 'right' }, sub: { x: 16, y: 19.5, w: 78, h: 6, align: 'right' }, dev: { x: -6, y: 33, w: 64, rot: -7 } },
    'small': { title: { x: 6, y: 7, w: 88, h: 21, align: 'center' }, sub: { x: 8, y: 20.5, w: 84, h: 6, align: 'center' }, dev: { x: 24, y: 38, w: 52, rot: 0 } },
    'full': { title: { x: 6, y: 4, w: 88, h: 21, align: 'center' }, sub: { x: 8, y: 17.5, w: 84, h: 6, align: 'center' }, dev: { x: 0, y: 0, w: 100, rot: 0, frame: 'none', fit: 'cover', shadow: 0 } },
    'full-bottom': { title: { x: 6, y: 68, w: 88, h: 21, align: 'center' }, sub: { x: 8, y: 87.5, w: 84, h: 6, align: 'center' }, dev: { x: 0, y: 0, w: 100, rot: 0, frame: 'none', fit: 'cover', shadow: 0 } },
    'span-left': { title: { x: 6, y: 5, w: 88, h: 21, align: 'center' }, sub: { x: 8, y: 18.5, w: 84, h: 6, align: 'center' }, dev: { x: 50, y: 30, w: 92, rot: 0 } },
    'span-right': { title: { x: 6, y: 5, w: 88, h: 21, align: 'center' }, sub: { x: 8, y: 18.5, w: 84, h: 6, align: 'center' }, dev: { x: -42, y: 30, w: 92, rot: 0 } },
    'text-only': { title: { x: 6, y: 36, w: 88, h: 20, align: 'center' }, sub: { x: 8, y: 52, w: 84, h: 6, align: 'center' }, dev: null },
    'card': { title: { x: 8, y: 5, w: 84, h: 16, align: 'left' }, sub: { x: 8, y: 18, w: 84, h: 6, align: 'left' }, dev: { x: 8, y: 27, w: 84, rot: 0, frame: 'none', fit: 'top', shadow: 50 } },
    'mid': { title: { x: 6, y: 5, w: 88, h: 21, align: 'center' }, sub: { x: 8, y: 18.5, w: 84, h: 6, align: 'center' }, dev: { x: 14, y: 30, w: 72, rot: 0 } },
    'landscape': { title: { x: 5, y: 10, w: 40, h: 34, align: 'left' }, sub: { x: 5, y: 44, w: 40, h: 12, align: 'left' }, dev: { x: 50, y: 12, w: 46, rot: 0 } },
    'landscape-right': { title: { x: 55, y: 10, w: 40, h: 34, align: 'left' }, sub: { x: 55, y: 44, w: 40, h: 12, align: 'left' }, dev: { x: 4, y: 12, w: 46, rot: 0 } },
    'landscape-center': { title: { x: 10, y: 6, w: 80, h: 20, align: 'center' }, sub: { x: 15, y: 26, w: 70, h: 10, align: 'center' }, dev: { x: 22, y: 36, w: 56, rot: 0 } },
    'landscape-bottom': { title: { x: 10, y: 74, w: 80, h: 20, align: 'center' }, sub: { x: 15, y: 90, w: 70, h: 8, align: 'center' }, dev: { x: 22, y: 6, w: 56, rot: 0 } },
    'landscape-full': { title: { x: 6, y: 8, w: 88, h: 22, align: 'center' }, sub: { x: 15, y: 30, w: 70, h: 8, align: 'center' }, dev: { x: 0, y: 0, w: 100, rot: 0, frame: 'none', fit: 'cover', shadow: 0 } },
    'watch': { title: { x: 5, y: 5, w: 90, h: 24, align: 'center' }, sub: { x: 8, y: 26, w: 84, h: 8, align: 'center' }, dev: { x: 14, y: 34, w: 72, rot: 0, frame: 'watch' } },
    'watch-bottom': { title: { x: 5, y: 72, w: 90, h: 22, align: 'center' }, sub: { x: 8, y: 92, w: 84, h: 6, align: 'center' }, dev: { x: 14, y: 4, w: 72, rot: 0, frame: 'watch' } },
    'watch-full': { title: { x: 5, y: 6, w: 90, h: 22, align: 'center' }, sub: { x: 8, y: 26, w: 84, h: 8, align: 'center' }, dev: { x: 0, y: 0, w: 100, rot: 0, frame: 'none', fit: 'cover', shadow: 0 } },
    'mac': { title: { x: 6, y: 8, w: 88, h: 18, align: 'center' }, sub: { x: 15, y: 26, w: 70, h: 8, align: 'center' }, dev: { x: 10, y: 36, w: 80, rot: 0, frame: 'browser' } },
    'mac-left': { title: { x: 5, y: 12, w: 38, h: 34, align: 'left' }, sub: { x: 5, y: 46, w: 38, h: 12, align: 'left' }, dev: { x: 46, y: 14, w: 60, rot: 0, frame: 'browser' } },
    'vision': { title: { x: 6, y: 6, w: 88, h: 18, align: 'center' }, sub: { x: 15, y: 24, w: 70, h: 8, align: 'center' }, dev: { x: 15, y: 32, w: 70, rot: 0, frame: 'none', radius: 3, shadow: 60 } },
  };


  /* ---- örnek metin bankası: şablon kopyası "ürün/ASO" konuşuyorsa kategoriye göre gerçek uygulama metniyle değiştirilir ---- */
  const META = /appscreens|screenshot|\baso\b|template|app store|conversion|download|localis|localiz|output|upload|a\/b|restyl|customis|customiz|pixel perfect|crisp export|caption/i;
  const B = (en, tr, sen, str) => [en, tr, sen, str];
  const BANK = {
    education: [B('Learn a little\n[every day]', '[Her gün]\nbiraz öğren', 'Five minutes is enough', 'Beş dakika yeter'), B('Lessons that\n[stick]', '[Kalıcı]\ndersler', 'Short, focused, spaced out', 'Kısa, odaklı, aralıklı'), B('Practice with\n[real] examples', '[Gerçek]\nörneklerle pratik', 'Feedback in the moment', 'Anında geri bildirim'), B('Keep your\n[streak] alive', '[Serini]\ncanlı tut', 'Small goals, big progress', 'Küçük hedef, büyük ilerleme'), B('Track what\nyou [master]', '[Öğrendiklerini]\nizle', 'See progress by topic', 'Konuya göre ilerleme'), B('Learn\n[offline]', '[Çevrimdışı]\nöğren', 'Download lessons for the road', 'Dersleri yola indir'), B('Made for\n[busy] people', '[Yoğun] insanlar\niçin', 'Fits between meetings', 'Toplantı aralarına sığar'), B('Start\n[today]', '[Bugün]\nbaşla', 'First lessons are free', 'İlk dersler ücretsiz')],
    finance: [B('See all your\n[money] at once', 'Tüm [paranı]\ntek bakışta gör', 'Every account in one place', 'Her hesap tek yerde'), B('Budget without\n[effort]', 'Zahmetsiz\n[bütçe]', 'Know the end of the month early', 'Ay sonunu önceden bil'), B('Catch\n[subscriptions]', '[Abonelikleri]\nyakala', 'The payments you forgot', 'Unuttuğun ödemeler'), B('Save toward\na [goal]', 'Bir [hedefe]\nbiriktir', 'Round-ups and rules', 'Yuvarlama ve kurallar'), B('Insights that\n[matter]', 'Önemli\n[içgörüler]', 'Where your money really goes', 'Paran gerçekten nereye gidiyor'), B('Bank-level\n[security]', 'Banka düzeyi\n[güvenlik]', 'Face ID and encryption', 'Face ID ve şifreleme'), B('Share with\nyour [partner]', '[Partnerinle]\npaylaş', 'Shared budgets, private accounts', 'Ortak bütçe, özel hesaplar'), B('Start\n[free]', '[Ücretsiz]\nbaşla', 'No card needed', 'Kart gerekmez')],
    'health & fitness': [B('Feel better\n[every day]', '[Her gün]\ndaha iyi hisset', 'Small habits that add up', 'Biriken küçük alışkanlıklar'), B('Workouts that\n[fit] you', 'Sana [uyan]\nantrenmanlar', 'From 5 to 50 minutes', '5 ile 50 dakika arası'), B('Track your\n[progress]', '[İlerlemeni]\nizle', 'Weight, sleep, steps, mood', 'Kilo, uyku, adım, ruh hali'), B('Sleep\n[deeper]', 'Daha [derin]\nuyu', 'Wind-down routines that work', 'İşe yarayan uyku rutinleri'), B('Eat well,\n[simply]', '[Basitçe]\niyi beslen', 'Meals without the math', 'Hesap yapmadan öğünler'), B('Stay\n[motivated]', '[Motive]\nkal', 'Streaks, badges, reminders', 'Seri, rozet, hatırlatma'), B('Works with\nyour [watch]', '[Saatinle]\nçalışır', 'Apple Health and Google Fit', 'Apple Health ve Google Fit'), B('Start your\n[first] week', '[İlk] haftana\nbaşla', 'Free, no pressure', 'Ücretsiz, baskısız')],
    productivity: [B('Plan your\n[day] in seconds', '[Gününü]\nsaniyede planla', 'Tasks, events and focus together', 'Görev, etkinlik ve odak bir arada'), B('Capture\n[anything]', '[Her şeyi]\nyakala', 'Notes, links, voice, photos', 'Not, bağlantı, ses, fotoğraf'), B('Focus without\n[distractions]', '[Dikkat dağıtmadan]\nodaklan', 'Timers that respect your flow', 'Akışına saygılı sayaçlar'), B('Everything\n[in sync]', 'Her şey\n[eşitlenmiş]', 'Phone, tablet and desktop', 'Telefon, tablet ve masaüstü'), B('Weekly\n[review]', 'Haftalık\n[bakış]', 'See what moved the needle', 'Neyin işe yaradığını gör'), B('Share with\nyour [team]', '[Ekibinle]\npaylaş', 'Comments, assignments, due dates', 'Yorum, atama, tarih'), B('Private by\n[default]', '[Varsayılan]\nolarak özel', 'Your data stays yours', 'Verin sende kalır'), B('Get\n[started]', '[Hemen]\nbaşla', 'Free forever plan', 'Ömür boyu ücretsiz plan')],
    'social networking': [B('Find your\n[people]', '[İnsanlarını]\nbul', 'Communities around what you love', 'Sevdiğin şeylerin toplulukları'), B('Share the\n[moment]', '[Anı]\npaylaş', 'Photos, clips and stories', 'Fotoğraf, klip ve hikâye'), B('Chat that\n[feels] close', '[Yakın] hissettiren\nsohbet', 'Voice notes, reactions, calls', 'Sesli not, tepki, arama'), B('Never miss\na [reply]', 'Hiçbir [yanıtı]\nkaçırma', 'Smart, quiet notifications', 'Akıllı, sessiz bildirimler'), B('Meet people\n[nearby]', '[Yakınındaki]\ninsanlarla tanış', 'Events and meetups this week', 'Bu haftaki etkinlikler'), B('Safe by\n[design]', 'Tasarımı gereği\n[güvenli]', 'Verified profiles, easy blocking', 'Doğrulanmış profil, kolay engelleme'), B('Your feed,\n[your] rules', 'Akışın,\n[senin] kuralların', 'No algorithm surprises', 'Algoritma sürprizi yok'), B('Join\n[free]', '[Ücretsiz]\nkatıl', 'Takes thirty seconds', 'Otuz saniye sürer')],
    'food & drink': [B('Dinner,\n[sorted]', 'Akşam yemeği\n[hazır]', 'Recipes for what you have', 'Elindekilere göre tarifler'), B('Order in\n[seconds]', '[Saniyede]\nsipariş', 'Your usual, one tap away', 'Her zamankin tek dokunuşta'), B('Track it\n[live]', '[Canlı]\ntakip et', 'From kitchen to your door', 'Mutfaktan kapına'), B('Discover\n[local] favourites', '[Yerel]\nfavorileri keşfet', 'Rated by real neighbours', 'Gerçek komşular puanladı'), B('Plan the\n[week]', '[Haftayı]\nplanla', 'Shopping list builds itself', 'Alışveriş listesi kendiliğinden'), B('Eat well\non a [budget]', '[Bütçeyle]\niyi beslen', 'Deals every day', 'Her gün fırsat'), B('Save what\nyou [love]', '[Sevdiğini]\nkaydet', 'Collections and notes', 'Koleksiyon ve notlar'), B('First order\n[free] delivery', 'İlk siparişte\n[ücretsiz] teslimat', 'Start today', 'Bugün başla')],
    games: [B('Play\n[anywhere]', '[Her yerde]\noyna', 'Works offline', 'Çevrimdışı çalışır'), B('Hundreds of\n[levels]', 'Yüzlerce\n[bölüm]', 'New ones every week', 'Her hafta yenisi'), B('Epic\n[boosters]', 'Epik\n[güçler]', 'Turn the tide in one move', 'Tek hamlede tersine çevir'), B('Daily\n[rewards]', 'Günlük\n[ödüller]', 'Log in, collect, level up', 'Gir, topla, yüksel'), B('Play with\n[friends]', 'Arkadaşlarla\n[oyna]', 'Leaderboards and gifts', 'Liderlik tablosu ve hediye'), B('Build your\n[world]', '[Dünyanı]\nkur', 'Collect, craft, decorate', 'Topla, yap, süsle'), B('No\n[ads] mode', '[Reklamsız]\nmod', 'Focus on the fun', 'Eğlenceye odaklan'), B('Free to\n[play]', 'Ücretsiz\n[oyna]', 'Start now', 'Şimdi başla')],
    travel: [B('Plan your\n[next] trip', '[Sıradaki]\ngezini planla', 'Flights, stays and days in one place', 'Uçuş, konaklama ve günler tek yerde'), B('Book stays\nin [seconds]', '[Saniyeler] içinde\nkonaklama', 'Member prices included', 'Üye fiyatları dahil'), B('Real-time\n[flight] status', 'Gerçek zamanlı\n[uçuş] durumu', 'Gates, delays, baggage', 'Kapı, gecikme, bagaj'), B('Explore like\na [local]', '[Yerli] gibi\nkeşfet', 'Hidden spots, honest tips', 'Gizli yerler, dürüst ipuçları'), B('Works\n[offline]', '[Çevrimdışı]\nçalışır', 'Maps and tickets without signal', 'Sinyalsiz harita ve bilet'), B('Split costs\n[fairly]', 'Masrafları\n[adil] böl', 'Everyone pays their share', 'Herkes payını öder'), B('Collect your\n[memories]', '[Anılarını]\ntopla', 'One album per trip', 'Her geziye bir albüm'), B('Start\n[exploring]', '[Keşfetmeye]\nbaşla', 'Free to download', 'Ücretsiz indir')],
    shopping: [B('Shop\n[smarter]', 'Daha [akıllı]\nalışveriş', 'Compare before you buy', 'Almadan karşılaştır'), B('Deals\n[every day]', '[Her gün]\nfırsat', 'Only the ones you care about', 'Sadece ilgilendiklerin'), B('Try before\nyou [buy]', '[Almadan]\ndene', 'See it in your room', 'Odanda gör'), B('Checkout in\n[two taps]', '[İki dokunuşta]\nödeme', 'Saved cards and addresses', 'Kayıtlı kart ve adres'), B('Track every\n[order]', 'Her [siparişi]\ntakip et', 'Live from warehouse to door', 'Depodan kapına canlı'), B('Save your\n[wish list]', '[İstek listeni]\nkaydet', 'Price drop alerts', 'Fiyat düşüş uyarıları'), B('Easy\n[returns]', 'Kolay\n[iade]', 'No questions, no labels', 'Soru yok, etiket yok'), B('Start\n[shopping]', '[Alışverişe]\nbaşla', 'Free delivery on first order', 'İlk siparişte ücretsiz teslimat')],
    music: [B('Music for\n[every] moment', '[Her] ana\nmüzik', 'Playlists picked for you', 'Sana seçilmiş listeler'), B('Lyrics that\n[move] with you', 'Seninle [akan]\nsözler', 'Sing along in real time', 'Gerçek zamanlı eşlik'), B('Download and\nlisten [offline]', 'İndir, [çevrimdışı]\ndinle', 'No signal, no problem', 'Sinyal yok, sorun yok'), B('Hi-fi\n[sound]', 'Hi-fi\n[ses]', 'Lossless on every device', 'Her cihazda kayıpsız'), B('Share with\n[friends]', '[Arkadaşlarla]\npaylaş', 'Blend your tastes', 'Zevklerinizi karıştır'), B('Podcasts worth\nyour [time]', 'Zamanına [değer]\npodcastler', 'Chapters, speed, sleep timer', 'Bölüm, hız, uyku sayacı'), B('Identify\n[any] song', '[Her] şarkıyı\ntanı', 'Tap once', 'Tek dokun'), B('Try premium\n[free]', 'Premium\'u [ücretsiz]\ndene', 'Cancel anytime', 'İstediğin an iptal')],
    'photo & video': [B('Edit like\na [pro]', '[Pro] gibi\ndüzenle', 'Presets, curves, masks', 'Ön ayar, eğri, maske'), B('One tap\n[looks]', 'Tek dokunuşta\n[görünüm]', 'Film, portrait, cinematic', 'Film, portre, sinematik'), B('Cut video\n[fast]', 'Videoyu [hızla]\nkes', 'Trim, captions, music', 'Kırp, altyazı, müzik'), B('Remove\n[backgrounds]', '[Arka planı]\nkaldır', 'Clean edges in a second', 'Bir saniyede temiz kenar'), B('Batch\n[edit]', 'Toplu\n[düzenle]', 'Same look on 100 photos', '100 fotoğrafa aynı görünüm'), B('Export\n[lossless]', 'Kayıpsız\n[aktar]', 'Original resolution kept', 'Orijinal çözünürlük korunur'), B('Organise\nby [face]', '[Yüze] göre\ndüzenle', 'Find anyone instantly', 'Herkesi anında bul'), B('Start\n[creating]', '[Üretmeye]\nbaşla', 'Free tools included', 'Ücretsiz araçlar dahil')],
    utilities: [B('Simple tools,\n[done] right', 'Basit araçlar,\n[doğru] yapılmış', 'No clutter, no ads', 'Dağınıklık yok, reklam yok'), B('Works\n[offline]', '[Çevrimdışı]\nçalışır', 'Everything on your device', 'Her şey cihazında'), B('Sync\n[everywhere]', '[Her yerde]\neşitle', 'Phone, tablet, desktop', 'Telefon, tablet, masaüstü'), B('Private by\n[default]', '[Varsayılan]\nolarak özel', 'End-to-end encrypted', 'Uçtan uca şifreli'), B('Fast\n[search]', 'Hızlı\n[arama]', 'Find anything in a second', 'Her şeyi bir saniyede bul'), B('Widgets and\n[shortcuts]', 'Widget ve\n[kısayollar]', 'One tap from the home screen', 'Ana ekrandan tek dokunuş'), B('Backups you\ncan [trust]', '[Güvenebileceğin]\nyedekler', 'Automatic, versioned', 'Otomatik, sürümlü'), B('Get\n[started]', '[Hemen]\nbaşla', 'Free to use', 'Ücretsiz kullan')],
    business: [B('Run your\n[business] anywhere', '[İşini]\nher yerden yönet', 'Invoices, clients, payments', 'Fatura, müşteri, ödeme'), B('Invoices in\n[seconds]', '[Saniyede]\nfatura', 'Templates that look professional', 'Profesyonel görünen şablonlar'), B('Get paid\n[faster]', 'Daha [hızlı]\nödeme al', 'Cards, links, reminders', 'Kart, bağlantı, hatırlatma'), B('See the\n[numbers]', '[Rakamları]\ngör', 'Cash flow at a glance', 'Nakit akışı bir bakışta'), B('Work with\nyour [team]', '[Ekibinle]\nçalış', 'Roles and permissions', 'Rol ve izinler'), B('Export to\n[accounting]', '[Muhasebeye]\naktar', 'Excel, CSV, your accountant', 'Excel, CSV, muhasebecin'), B('Secure by\n[design]', 'Tasarımı gereği\n[güvenli]', 'Two-factor and audit logs', 'İki faktör ve denetim kaydı'), B('Start\n[free]', '[Ücretsiz]\nbaşla', 'No card needed', 'Kart gerekmez')],
    lifestyle: [B('Make room for\nwhat [matters]', '[Önemli] olana\nyer aç', 'Small rituals, big change', 'Küçük ritüel, büyük değişim'), B('Build\n[habits]', '[Alışkanlık]\nkur', 'One tap to check in', 'Tek dokunuşla işaretle'), B('Track your\n[mood]', '[Ruh halini]\nizle', 'Patterns you can act on', 'Harekete geçebileceğin kalıplar'), B('Plan your\n[week]', '[Haftanı]\nplanla', 'Meals, moves, moments', 'Öğün, hareket, an'), B('Gentle\n[reminders]', 'Nazik\n[hatırlatmalar]', 'Never nagging', 'Asla dırdır yok'), B('Share with\nsomeone', 'Biriyle\npaylaş', 'Accountability, kindly', 'Nazikçe hesap verebilirlik'), B('Insights\n[weekly]', '[Haftalık]\niçgörüler', 'See what helped', 'Neyin yardım ettiğini gör'), B('Start\n[today]', '[Bugün]\nbaşla', 'Free to try', 'Ücretsiz dene')],
    entertainment: [B('Stream what\nyou [love]', '[Sevdiğini]\nizle', 'Series, films, live', 'Dizi, film, canlı'), B('Watch\n[anywhere]', '[Her yerde]\nizle', 'Phone, TV, tablet', 'Telefon, TV, tablet'), B('Download and\nwatch [offline]', 'İndir, [çevrimdışı]\nizle', 'Perfect for flights', 'Uçuşlar için ideal'), B('Picked\n[for you]', '[Senin için]\nseçildi', 'Recommendations that get it', 'Anlayan öneriler'), B('Never miss\nan [episode]', 'Hiçbir [bölümü]\nkaçırma', 'Reminders on release', 'Yayında hatırlatma'), B('Profiles for\nthe [family]', '[Aile] için\nprofiller', 'Kids mode included', 'Çocuk modu dahil'), B('Crisp\n[4K]', 'Net\n[4K]', 'With Dolby sound', 'Dolby sesle'), B('Start\n[watching]', '[İzlemeye]\nbaşla', 'First month free', 'İlk ay ücretsiz')],
    'developer tools': [B('Ship\n[faster]', 'Daha [hızlı]\nyayınla', 'From commit to store in minutes', 'Commit\'ten mağazaya dakikalar'), B('Logs in\n[real time]', '[Gerçek zamanlı]\nkayıtlar', 'Filter, search, share', 'Filtrele, ara, paylaş'), B('Monitor\n[everything]', '[Her şeyi]\nizle', 'Crashes, latency, usage', 'Çökme, gecikme, kullanım'), B('Automate the\n[boring] parts', '[Sıkıcı] kısımları\notomatikleştir', 'Scripts and integrations', 'Betik ve entegrasyonlar'), B('Works with\nyour [stack]', '[Altyapınla]\nçalışır', 'Git, CI, cloud', 'Git, CI, bulut'), B('Secure by\n[default]', '[Varsayılan]\nolarak güvenli', 'Keys never leave your device', 'Anahtarlar cihazından çıkmaz'), B('Team\n[dashboards]', 'Ekip\n[panoları]', 'Everyone sees the same truth', 'Herkes aynı gerçeği görür'), B('Start\n[free]', '[Ücretsiz]\nbaşla', 'Open source core', 'Açık kaynak çekirdek')],
    medical: [B('Care that\n[fits] your life', 'Hayatına [uyan]\nbakım', 'Appointments, records, reminders', 'Randevu, kayıt, hatırlatma'), B('Never miss\na [dose]', 'Hiçbir [dozu]\nkaçırma', 'Smart medication reminders', 'Akıllı ilaç hatırlatma'), B('Track\n[symptoms]', '[Belirtileri]\nizle', 'Share with your doctor', 'Doktorunla paylaş'), B('Book in\n[seconds]', '[Saniyede]\nrandevu', 'Video or in person', 'Görüntülü ya da yüz yüze'), B('Your records,\n[in one place]', 'Kayıtların\n[tek yerde]', 'Labs, prescriptions, history', 'Tahlil, reçete, geçmiş'), B('Private and\n[secure]', 'Özel ve\n[güvenli]', 'Encrypted, never sold', 'Şifreli, asla satılmaz'), B('Made with\n[clinicians]', '[Klinisyenlerle]\nyapıldı', 'Evidence-based', 'Kanıta dayalı'), B('Get\n[started]', '[Hemen]\nbaşla', 'Free for patients', 'Hastalara ücretsiz')],
    sports: [B('Train\n[smarter]', 'Daha [akıllı]\nantrenman', 'Plans that adapt to you', 'Sana uyum sağlayan planlar'), B('Track every\n[session]', 'Her [seansı]\nkaydet', 'Pace, power, heart rate', 'Tempo, güç, nabız'), B('Live\n[scores]', 'Canlı\n[skorlar]', 'Every league, every match', 'Her lig, her maç'), B('Compete with\n[friends]', '[Arkadaşlarla]\nyarış', 'Weekly challenges', 'Haftalık meydan okumalar'), B('Coaches\non [demand]', '[İstediğin an]\nkoç', 'Video feedback in a day', 'Bir günde video geri bildirim'), B('Works with\nyour [watch]', '[Saatinle]\nçalışır', 'Garmin, Apple, Wear OS', 'Garmin, Apple, Wear OS'), B('Recover\n[well]', '[İyi]\ntoparlan', 'Sleep and load balance', 'Uyku ve yük dengesi'), B('Start\n[today]', '[Bugün]\nbaşla', 'Free plan included', 'Ücretsiz plan dahil')],
    weather: [B('Weather you\ncan [trust]', '[Güvenebileceğin]\nhava durumu', 'Minute-by-minute rain', 'Dakika dakika yağmur'), B('Plan\n[every] hour', '[Her] saati\nplanla', 'Hourly and 10-day forecasts', 'Saatlik ve 10 günlük tahmin'), B('Severe\n[alerts]', 'Şiddetli hava\n[uyarıları]', 'Before it hits', 'Gelmeden önce'), B('Radar in\n[real time]', '[Gerçek zamanlı]\nradar', 'See the storm move', 'Fırtınanın hareketini gör'), B('Widgets for\nyour [day]', '[Günün] için\nwidget\'lar', 'A glance is enough', 'Bir bakış yeter'), B('Air, UV\nand [pollen]', 'Hava, UV\nve [polen]', 'Everything that affects you', 'Seni etkileyen her şey'), B('Works\n[offline]', '[Çevrimdışı]\nçalışır', 'Last forecast always cached', 'Son tahmin hep hazır'), B('Free,\n[no ads]', 'Ücretsiz,\n[reklamsız]', 'Download today', 'Bugün indir')],
  };
  BANK.reference = BANK.education; BANK.books = BANK.education; BANK.navigation = BANK.travel; BANK['graphics & design'] = BANK['photo & video']; BANK.news = BANK.entertainment; BANK['magazines & newspapers'] = BANK.entertainment;
  const BRAND_RE = /app\s?screens/gi;
  const isMeta = (sc) => sc.title && typeof sc.title === 'object' && META.test(sc.title.en || '');
  function sanitize(spec) {
    if (spec.name) spec.name = spec.name.replace(/^Inspired (by|from) /i, '').replace(/^Free Inspired by /i, 'Free ').replace(/^Landscape: Inspired by /i, 'Landscape: ').replace(/^MacOS Inspired by /i, 'MacOS ');
    const screens = spec.screens || [];
    const meta = screens.filter(isMeta).length >= 2;
    const bank = BANK[(spec.cats || []).find((c) => BANK[c])] || BANK.lifestyle;
    screens.forEach((sc, i) => {
      const b = bank[i % bank.length];
      if (meta && sc.title && typeof sc.title === 'object' && (sc.title.en || '').trim()) {
        const keepUpper = /^[A-Z0-9\s\[\].,!?'&+-]+$/.test(sc.title.en) && /[A-Z]/.test(sc.title.en);
        sc.title = { en: keepUpper ? b[0].toUpperCase() : b[0], tr: keepUpper ? b[1].toLocaleUpperCase('tr') : b[1] };
        if (sc.sub && typeof sc.sub === 'object') sc.sub = { en: b[2], tr: b[3] };
      } else if (sc.title && typeof sc.title === 'object') {
        sc.title = { en: (sc.title.en || '').replace(BRAND_RE, 'this app'), tr: (sc.title.tr || '').replace(BRAND_RE, 'bu uygulama') };
        if (sc.sub && typeof sc.sub === 'object') sc.sub = { en: (sc.sub.en || '').replace(BRAND_RE, 'this app'), tr: (sc.sub.tr || '').replace(BRAND_RE, 'bu uygulama') };
      }
      (sc.els || []).forEach((e) => {
        if (e.kind === 'icon') { const nm = typeof e.text === 'string' ? e.text : (e.text && e.text.en) || ''; if (!nm || BRAND_RE.test(nm)) e.text = { en: 'Your App', tr: 'Uygulaman' }; }
        else if (e.text) { const T = typeof e.text === 'string' ? { en: e.text } : e.text; Object.keys(T).forEach((k) => { if (BRAND_RE.test(T[k])) T[k] = T[k].replace(BRAND_RE, k === 'tr' ? 'bu uygulama' : 'this app'); }); e.text = T; }
      });
    });
    return spec;
  }

  function expand(spec) {
    sanitize(spec);
    const st = Object.assign({ font: 'inter', weight: 800, size: 6.2, color: '#111214', accent: '#6c5ce7', hlStyle: 'color', letterSpacing: -1.5, lineHeight: 1.1, subSize: 3.1, subWeight: 500, subOpacity: 70 }, spec.style || {});
    const dev = Object.assign({ frame: 'iphone-pro', color: 'graphite', shadow: 45, glare: true, fit: 'top', homeIndicator: true }, spec.device || {});
    const screens = (spec.screens || []).map((sc, i) => {
      const lay = LAYOUTS[sc.layout || spec.layout || 'text-top'] || LAYOUTS['text-top'];
      const layers = [];
      const titleBox = Object.assign({}, lay.title, st.titleBox || {}, sc.titleBox || {});
      const subBox = Object.assign({}, lay.sub, st.subBox || {}, sc.subBox || {});
      (sc.under || []).forEach((e) => layers.push(newLayer('element', Object.assign({}, e, { text: e.text == null ? undefined : (typeof e.text === 'string' ? { en: e.text } : e.text) }))));
      if (sc.title != null) layers.push(newLayer('text', Object.assign({ role: 'title', name: 'Title', text: typeof sc.title === 'string' ? { en: sc.title } : sc.title },
        { font: st.font, weight: st.weight, size: st.size, color: st.color, accent: st.accent, hlStyle: st.hlStyle, letterSpacing: st.letterSpacing, lineHeight: st.lineHeight, uppercase: !!st.uppercase, decoration: st.decoration || 'none', box: st.box || 'none', boxColor: st.boxColor || '#ffffff', boxOpacity: st.boxOpacity ?? 100, boxRadius: st.boxRadius ?? 3, shadow: !!st.shadow, hlTextColor: st.hlTextColor, gradient: st.gradient },
        titleBox, sc.titleStyle || {})));
      if (sc.sub != null && sc.sub !== false) layers.push(newLayer('subtitle', Object.assign({ role: 'subtitle', name: 'Subtitle', text: typeof sc.sub === 'string' ? { en: sc.sub } : sc.sub },
        { font: st.subFont || st.font, weight: st.subWeight, size: st.subSize, color: st.subColor || st.color, opacity: st.subOpacity, letterSpacing: st.subLetterSpacing ?? 0, lineHeight: 1.2, uppercase: !!st.subUppercase, flow: st.subFlow !== false, flowGap: st.subGap ?? 1.2 },
        subBox, sc.subStyle || {})));
      const d = sc.dev === null ? null : Object.assign({}, lay.dev || {}, dev, sc.dev || {});
      if (d && lay.dev !== null && sc.dev !== null) layers.push(newLayer('device', Object.assign({ name: 'Device' }, d)));
      (sc.els || []).forEach((e) => layers.push(newLayer('element', Object.assign({}, e, { text: e.text == null ? undefined : (typeof e.text === 'string' ? { en: e.text } : e.text) }))));
      (sc.extra || []).forEach((L) => layers.push(newLayer(L.type, L)));
      // katman sırası: device önce (arka) mı? spec.deviceAbove → cihaz metnin üstünde
      if (spec.deviceAbove || sc.deviceAbove) { const di = layers.findIndex((L) => L.type === 'device'); if (di >= 0) { const [D] = layers.splice(di, 1); layers.push(D); } }
      else { const di = layers.findIndex((L) => L.type === 'device'); if (di >= 0) { const [D] = layers.splice(di, 1); layers.unshift(D); } }
      // elementler en üstte kalsın; metinler cihazın üstünde (bleed/full düzenlerde okunabilirlik)
      const bg = Object.assign({}, spec.bg || {}, sc.bg || {});
      if (spec.panorama && sc.bg == null) bg.panorama = true;
      return { name: sc.name || '', bg, layers };
    });
    return {
      key: spec.key, name: spec.name, desc: spec.desc || {}, tags: spec.tags || [], cats: spec.cats || [], theme: spec.theme || 'light', skill: spec.skill || 'simple', free: !!spec.free,
      archived: !!spec.archived, collection: spec.collection || null, orientation: spec.orientation || 'portrait', devices: spec.devices || ['iphone', 'ipad', 'android'], sizes: spec.sizes || null, background: spec.panorama ? Object.assign({}, spec.pbg || spec.bg || {}) : null,
      screens, spec,
    };
  }

  global.TplDSL = { LAYOUTS, expand, BANK, sanitize };
  global.TEMPLATES = global.TEMPLATES || [];
  global.defineTemplate = (spec) => { const t = expand(spec); const i = global.TEMPLATES.findIndex((x) => x.key === t.key); if (i >= 0) global.TEMPLATES[i] = t; else global.TEMPLATES.push(t); return t; };
})(typeof window !== 'undefined' ? window : globalThis);
