from pathlib import Path
import shutil,zipfile,json,re,html
r=Path(__file__).resolve().parent.parent
langs=['en','tr','de','fr','es','it','pt','ja'];data={l:{} for l in langs}
for i,line in enumerate((r/'locales/site.tsv').read_text().splitlines(),1):
 row=line.split('|');assert len(row)==8,(i,len(row))
 for l,value in zip(langs,row):data[l][row[0]]=value
for i,line in enumerate((r/'locales/ui.tsv').read_text().splitlines(),1):
 row=line.split('|');assert len(row)==7,(i,len(row))
 for l,value in zip(['en','de','fr','es','it','pt','ja'],row):data[l][row[0]]=value
(r/'engine/site-locales.js').write_text('/* Generated by scripts/build.py from locales/*.tsv. */\nwindow.FRAMEGROVE_LOCALES='+json.dumps(data,ensure_ascii=False,separators=(',',':'))+';\n')
out=r/'public'
if out.exists():shutil.rmtree(out)
out.mkdir()
for n in ['app','engine','templates','mcp','creative-assets','iphone-duo','privacy','skills','common.js','fonts.css','site.css','landing.css','landing.js','guide.css','index.html','index.md','llms.txt','llms-full.txt','robots.txt','sitemap.xml','favicon.svg','social.png']:
 source=r/n
 if source.is_dir():
  if n=='mcp':
   (out/n).mkdir()
   for file in ['index.html','index.md']:shutil.copy2(source/file,out/n/file)
  else:shutil.copytree(source,out/n)
 elif source.exists():shutil.copy2(source,out/n)
base='https://framegrove.bamstudio.dev'
hreflang='\n'.join(f'<link rel="alternate" hreflang="{l}" href="{base}{"/" if l=="en" else "/"+l+"/"}">' for l in langs)+'\n<link rel="alternate" hreflang="x-default" href="'+base+'/">'
source=(r/'index.html').read_text()
# Marketing translations are embedded in static HTML for search engines and JS-free reading.
pattern=re.compile(r'<(?P<tag>\w+)(?P<attrs>[^>]*\bdata-t(?:\s|>)[^>]*)>(?P<text>[^<]*)</(?P=tag)>')
# Match data-t at the end of an attribute list as well.
pattern=re.compile(r'<(?P<tag>\w+)(?P<attrs>[^>]*\bdata-t\b[^>]*)>(?P<text>[^<]*)</(?P=tag)>')
for l in langs:
 def translate(m):
  key=html.unescape(m['text']).strip();value=data[l].get(key,key)
  if key not in data[l]:raise ValueError('Missing landing translation: '+key)
  attrs=m['attrs']+' data-t-orig="'+html.escape(key,quote=True)+'"'
  return '<'+m['tag']+attrs+'>'+html.escape(value)+'</'+m['tag']+'>'
 page=pattern.sub(translate,source)
 path='/' if l=='en' else '/'+l+'/'
 page=page.replace('<html lang="en">',f'<html lang="{l}">').replace('<head>','<head><base href="/">')
 page=page.replace('href="'+base+'/"','href="'+base+path+'"').replace('content="'+base+'/"','content="'+base+path+'"')
 if l!='en':
  title=data[l]['iPhone Duo screenshot generator']+' & Creative Assets — Framegrove'
  page=re.sub(r'<title>.*?</title>','<title>'+html.escape(title)+'</title>',page)
  page=re.sub(r'<meta name="description"[^>]*>','<meta name="description" content="'+html.escape(data[l]['Make the scroll stop. Design App Store Creative Assets and iPhone Duo screenshots with a real editor, thoughtful templates and your real app.'],quote=True)+'">',page)
 page=page.replace('</head>',hreflang+'\n</head>')
 target=out if l=='en' else out/l;target.mkdir(exist_ok=True);(target/'index.html').write_text(page)
for name in ['templates','mcp','creative-assets','iphone-duo','privacy']:
 p=out/name/'index.html';page=p.read_text();page=page.replace('</head>','<link rel="describedby" href="/llms.txt"><link rel="alternate" type="text/markdown" href="index.md"></head>');p.write_text(page)
urls=['/','/templates/','/mcp/','/creative-assets/','/iphone-duo/','/privacy/']+['/'+l+'/' for l in langs if l!='en']
(out/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+base+p+'</loc></url>' for p in urls)+'</urlset>')
(out/'downloads').mkdir()
with zipfile.ZipFile(out/'downloads/framegrove-mcp.zip','w',zipfile.ZIP_DEFLATED) as z:
 for folder in ['engine','mcp']:
  for p in sorted((r/folder).rglob('*')):
   rel=p.relative_to(r)
   if p.is_file() and not {'node_modules','fonts'}.intersection(rel.parts) and p.name not in ['index.html','index.md']:z.write(p,'framegrove-mcp/'+str(rel))
 for file in ['README.md','LICENSE']:z.write(r/file,'framegrove-mcp/'+file)
with zipfile.ZipFile(out/'downloads/framegrove-skill.zip','w',zipfile.ZIP_DEFLATED) as z:
 for p in sorted((r/'skills/framegrove').rglob('*')):
  if p.is_file():z.write(p,p.relative_to(r/'skills'))
print(f'Built {len(langs)} static language pages, documentation, MCP and skill downloads.')
